project:
  type: website
  output-dir: docs

website:
  title: "Adrián **Zancajo**"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: CV.pdf
        text: CV  
      - href: publications.qmd
        text: Publications
      - outreach.qmd

  page-footer:
    background: light # or `dark`

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    page-layout: article

editor: visual
