project:
  type: website
  output-dir: docs

website:
  title: "Adrián **Zancajo**"
  site-url: https://azancajo.github.io
  description: "Ramón y Cajal Researcher at the Autonomous University of Barcelona specializing in education privatization, school markets, and educational inequality."
  open-graph:
    description: "Ramón y Cajal Researcher at the Autonomous University of Barcelona specializing in education privatization, school markets, and educational inequality."
    image: images/prof_pic2.jpg
  twitter-card:
    creator: "@AdrianZancajo"
    description: "Ramón y Cajal Researcher at the Autonomous University of Barcelona specializing in education privatization, school markets, and educational inequality."
    image: images/prof_pic2.jpg
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: CV.pdf
        text: CV
      - href: research-lines.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - outreach.qmd

  page-footer:
    background: light # or `dark`

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    page-layout: article

editor: visual
