project:
  type: website
  output-dir: docs

website:
  title: "Adrián **Zancajo**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - Research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

