---
title: "Bio"
html:
toc: false
---

I am a Ramón y Cajal researcher at the Department of Sociology of the UAB. My research areas are education privatisation and markets, educational policies and inequalities. In these areas, I have developed different research lines, including the political economy of education reforms, the enactment of education policies and their impact on equity.

Before joining the UAB, I has been a postdoctoral fellow at the Catholic University of Louvain and the University of Glasgow, and a lecturer in education at the University of Manchester. I have participated in different competitive international research projects as a principal investigator and researcher. I have also co-led and participated in research contracts and consultancies for institutions and organisations such as UNESCO, British Academy, Open Society Foundations, Education International, Barcelona Education Consortium, Fundació Jaume Bofill, and Childhood and Adolescence Institute, among others.

### You can download my CV [here](https://drive.google.com/file/d/1LPddJ4-eEHKZolOO827LpiQij1fY68jn/view?usp=sharing)
