---
title: "Research"
format: html
---

## Journal articles {#journal-articles}

-   Fontdevila, C., Zancajo, A., & Verger, A. (2024). [Catholic Schools in the Marketplace: Changing and Enduring Religious Identities](https://www.tandfonline.com/doi/epdf/10.1080/0161956X.2024.2381393?needAccess=true). *Peabody Journal of Education*, *99*(4), 464–481.

-   Bonal, X., Pagès, M., Verger, A., & Zancajo, A. (2023). [Regional policy trajectories in the Spanish education system: Different uses of relative autonomy](https://epaa.asu.edu/index.php/epaa/article/view/8031/3120). *Education Policy Analysis Archives*, *31*.

-   Aldinucci, A., Valiente, O., Hurrell, S., & Zancajo, A. (2023). [Understanding aspirations: why do secondary TVET students aim so high in Chile?](https://www.tandfonline.com/doi/epdf/10.1080/13636820.2021.1973543?needAccess=true). *Journal of Vocational Education & Training*, 1-22.

-   Zancajo, A., Verger, A., & Fontdevila, C. (2022). [The instrumentation of public subsidies for private schools: Different regulatory models with concurrent equity implications](https://journals.sagepub.com/doi/epub/10.1177/14749041211023339). *European Educational Research Journal*, *21*(1), 44-70.

-   Zancajo, A., Fontdevila, C., & Verger, A. (2022). [Las Alianzas Público-Privadas en educación: debates, modelos y horizontes regulativos en los países de la OCDE](https://revistas.uam.es/jospoe/article/view/14352/14758). *Journal of Supranational Policies of Education*, (15), 6–32.

-   Zancajo, A., & Bonal, X. (2022). [Education markets and school segregation: a mechanism-based explanation](https://www.researchgate.net/publication/347422570_Education_markets_and_school_segregation_a_mechanism-based_explanation). *Compare: A Journal of Comparative and International Education*, 58(8), 1241-1258.

-   Scandurra, R., Zancajo, A., & Bonal, X. (2022). [Opting out of neighbourhood schools: The role of local education markets in student mobility](https://onlinelibrary.wiley.com/doi/epdf/10.1002/psp.2542). *Population, Space and Place*, *28*(5), e2542.

-   Zancajo, A., Verger, A., & Bolea, P. (2022). [Digitalization and beyond: the effects of Covid-19 on post-pandemic educational policy and delivery in Europe](https://academic.oup.com/policyandsociety/article-pdf/41/1/111/46878820/puab016.pdf). *Policy and Society*, *41*(1), 111-128.

-   Bonal, X., Zancajo, A., & Scandurra, R. (2021). [Student mobility and school segregation in an (un) controlled choice system: A counterfactual approach](https://bera-journals.onlinelibrary.wiley.com/doi/epdf/10.1002/berj.3694). *British Educational Research Journal*, 47(1), 42-64.

-   Valiente, O., Sepúlveda, L., & Zancajo, A. (2021). [Development paradigms in the institutional configuration of vocational education and training in Chile (1964-2005)](https://www.tandfonline.com/doi/epdf/10.1080/13636820.2020.1833076?needAccess=true). *Journal of Vocational Education & Training*, *73*(2), 278-294.

-   Bonal, X., & Zancajo, A. (2020). [Elección de escuela, movilidad y segregación escolar del alumnado vulnerable en Barcelona](https://revistas.uam.es/reice/article/view/reice2020_18_4_008/12569). *REICE: Revista Iberoamericana sobre Calidad, Eficacia y Cambio en Educación*, 18(4), 197-218.

-   Zancajo, A. (2020). [Schools in the Marketplace: Analysis of School Supply Responses in the Chilean Education Market](https://journals.sagepub.com/doi/epub/10.1177/0895904819881781). *Educational Policy*, 34(1), 43-64.

-   Valiente, O., Zancajo, A., & Jacovkis, J. (2020). [The coordination of skill supply and demand in the market model of skill formation: testing the assumptions for the case of Chile](https://www.tandfonline.com/doi/epdf/10.1080/02601370.2019.1678692?needAccess=true). *International Journal of Lifelong Education*, *39*(1), 90-103.

-   Bonal, X., Zancajo, A., & Scandurra, R. (2019). [Residential segregation and school segregation of foreign students in Barcelona](https://www.researchgate.net/publication/335840990_Residential_segregation_and_school_segregation_of_foreign_students_in_Barcelona). *Urban Studies*, 56(15), 3251-3273.

-   Zancajo, A. (2019). [Education markets and schools’ mechanisms of exclusion: The case of Chile](https://epaa.asu.edu/index.php/epaa/article/view/4318/2325). *Education Policy Analysis Archives*, *27*(130).

-   Zancajo, A., & Valiente, O. (2019). [TVET policy reforms in Chile 2006–2018: between human capital and the right to education](https://www.tandfonline.com/doi/epdf/10.1080/13636820.2018.1548500?needAccess=true). *Journal of Vocational Education & Training*, *71*(4), 579-599.

-   Bonal, X., & Zancajo, A. (2018). [Demand rationalities in contexts of poverty: Do the Poor respond to market incentives in the same way?](https://www.researchgate.net/publication/323490216_Demand_rationalities_in_contexts_of_poverty_Do_the_Poor_respond_to_market_incentives_in_the_same_way). *International Journal of Educational Development*, *59*, 20-27.

-   Zancajo, A. (2018). [Educational providers in the marketplace: Schools’ marketing responses in Chile](https://www.researchgate.net/publication/321063384_Educational_providers_in_the_marketplace_Schools'_marketing_responses_in_Chile). *International Journal of Educational Research*, *88*, 166-176.

-   Verger, A., Fontdevila, C., & Zancajo, A. (2017). [Multiple paths towards education privatization in a globalizing world: A cultural political economy review](https://www.researchgate.net/publication/316196658_Multiple_paths_towards_education_privatization_in_a_globalizing_world_a_cultural_political_economy_review). *Journal of Education Policy*, *32*(6), 757-787.

-   Bonal, X., Verger, A., & Zancajo, A. (2017). [Making poor choices? Demand rationalities and school choice in a Chilean local education market](https://www.researchgate.net/publication/313660554_Making_Poor_Choices_Demand_Rationalities_and_School_Choice_in_a_Chilean_Local_Education_Market). *Journal of School Choice*, *11*(2), 258-281.

-   Valiente, O., & Zancajo, A. (2016). [La formación profesional en España: efectos sobre la empleabilidad en tiempos de crisis](http://educa.fcc.org.br/pdf/lc/v22n49/1981-0431-lc-22-49-00532.pdf). *Linhas Críticas*, *22*(49), 532-551.

-   Valiente, O., & Zancajo, A. (2016). [Formació professional i ocupabilitat a Catalunya](https://www.raco.cat/index.php/RECAT/article/download/389613/483030). *Revista econòmica de Catalunya*, (74), 51-60.

-   Verger, A., Zancajo, A., & Fontdevila, C. (2016). [La economía política de la privatización educativa: políticas, tendencias y trayectorias desde una perspectiva](https://revistas.pedagogica.edu.co/index.php/RCE/article/view/3764/3345). *Revista colombiana de educación*, (70), 47-78.

-   Verger, A., Bonal, X., & Zancajo, A. (2016). [What are the role and impact of public-private partnerships in education? A realist evaluation of the Chilean education quasi-market](https://www.researchgate.net/publication/299472482_What_Are_the_Role_and_Impact_of_Public-Private_Partnerships_in_Education_A_Realist_Evaluation_of_the_Chilean_Education_Quasi-Market). *Comparative Education Review*, *60*(2), 223-248.

-   Verger, A., Bonal, X., & Zancajo, A. (2016). [Recontextualización de políticas y (cuasi) mercados educativos. Un análisis de las dinámicas de demanda y oferta escolar en Chile](https://www.redalyc.org/articulo.oa?id=275043450052). *Education Policy Analysis Archives*, *24*, 27-27.

-   Bonal, X., & Zancajo, A. (2016). [Educació, pobresa i desigualtats en un context de crisi](https://www.researchgate.net/publication/313750984_Educacio_pobresa_i_desigualtats_en_un_context_de_crisi). *Nota d’economia*, *103*.

-   Castejón, A., & Zancajo, A. (2015). [Educational differentiation policies and the performance of disadvantaged students across OECD countries](https://journals.sagepub.com/doi/epub/10.1177/1474904115592489). *European Educational Research Journal*, *14*(3-4), 222-239.

-   Castejón, A., & Zancajo, A. (2015). Inclusión, desigualdades y diversidad en la educación obligatoria: retos para el sistema educativo español y evidencias internacionales. In *Organización y gestión educativa: Revista del Fórum Europeo de Administradores de la Educación*, 23(1), 20-24.

-   Zancajo, A., Bonal, X., & Verger, A. (2014). [Mercados educativos y segmentación de la oferta escolar: efectos sobre las desigualdades educativas en Chile](https://dialnet.unirioja.es/servlet/articulo?codigo=5035678&orden=0&info=link). *Témpora: Revista de historia y sociología de la educación*, *17*, 11-30.

## Books {#books-page}

-   Zancajo, A., Fontdevila, C., Jabbar, H., & Verger, A. (Eds.). (2025). [Research handbook on education privatization and marketization](https://www.elgaronline.com/edcollbook/book/9781035311385/9781035311385.xml). Edward Elgar Publishing.

-   Zancajo, A., & Bueno, C. (2024). [L'abandonament al batxillerat i als cicles formatius de grau mitjà](https://fundaciobofill.cat/uploads/docs/a/k/2/nbn-abandonamentbatxcicleformatius_061124.pdf). Barcelona: Fundació Jaume Bofill.

-   Zancajo, A., & Bueno, C. (2023). [L’abandonament a 4t d’ESO: les desigualtats en la transició a l’educació postobligatòria](https://fundaciobofill.cat/uploads/docs/w/b/l/15d-abandonament_zancajobueno020523.pdf). Barcelona: Fundació Jaume Bofill.

-   Zancajo, A., Verger, A., & Fontdevila, C. (2022). [La educación concertada en España](https://fundaciobofill.cat/uploads/docs/d/n/j/97z-laeducacionconcertada_281122_zancajovergerfontdevila.pdf). Barcelona: Fundació Jaume Bofill.

-   Zancajo, A., Verger, A., & Fontdevila, C. (2022). [La concertada a debat. Reformes contra les desigualtats educatives des d’una mirada internacional i comparada](https://fundaciobofill.cat/uploads/docs/v/l/l/lgb-pol90_concertada_040422.pdf). Barcelona: Fundació Jaume Bofill.

-   Verger, A., Fontdevila, C., & Zancajo, A. (2016). [The Privatization of Education. A Political Economy Approach to Global Education Reform](http://download.ei-ie.org/Docs/WebDepot/The_Privatization_of_Education.pdf). New York: Teachers College Press.

-   Bonal, X., Castejon, A., Zancajo, A., & Castel, J.L. (2015). [Equitat i resultats educatius a Catalunya. Una mirada a partir de PISA-2012](https://fundaciobofill.cat/uploads/docs/y/a/b/f/e/y/9/7/c/informesbreu60_xavierbonal.pdf). Barcelona: Fundació Jaume Bofill.

-   Valiente, O., Scandurra, R., Zancajo, A., & Brown, C. (2015). [Un model de formació professional dual per a Catalunya? Reptes en el disseny i implementació de la reforma](https://fundaciobofill.cat/sites/default/files/607.pdf). Barcelona: Fundació Jaume Bofill.

-   Valiente, O., Zancajo, A., & Tarriño, A. (2014). [La Formació professional i l’ocupació a Catalunya. Una ullada als indicadors des d’un prespectiva comparada](https://fundaciobofill.cat/uploads/old-files/Politiques%2082_WEB_seg.pdf). Barcelona: Fundació Jaume Bofill.

-   Ferrer, F., Castel, J.L., Castejón, A., & Zancajo, A. (2011). [PISA-2009: Avaluació de les desigualtats educatives a Catalunya](https://fundaciobofill.cat/uploads/docs/a/3/y/8/b/q/c/2/k/546.pdf). Barcelona: Editorial Mediterrània.

## Book chapters {#book-chapters}

-   Bonal, X., Fontdevila, C., & Zancajo, A. (2023). [The World Bank and education in a changing global arena](https://www.researchgate.net/publication/365585540_The_World_Bank_and_education_in_a_changing_global_arena). In R. J. Tierney, F. Rizvi, & K. Ercikan (Eds.), *International Encyclopedia of Education* (Fourth Edition) (pp. 480–487). Elsevier

-   Verger, A., Fontdevila, C., & Zancajo, A. (2023). [The privatization of education. Drivers, social effects and regulatory challenges of private sector participation in schooling](https://www.researchgate.net/publication/365607858_The_privatization_of_education_Drivers_social_effects_and_regulatory_challenges_of_private_sector_participation_in_schooling). In R. J. Tierney, F. Rizvi, & K. Ercikan (Eds.), *International Encyclopedia of Education* (Fourth Edition) (pp. 174–182). Elsevier

-   Zancajo, A., Fontdevila, C., & Verger, A. (2023). [Markets in Education and School Segregation: Paths of Problematization and Reform](https://www.researchgate.net/publication/372472164_Markets_in_Education_and_School_Segregation_Paths_of_Problematization_and_Reform). In: M. Verhoeven, J. Corvalán, V. Durpiez, & J.P. Valenzuela (Eds.) *Education Markets and Segregation*. Cham: Springer.

-   Zancajo, A., Verger, A., & Fontdevila, C. (2022). [Educational Privatization: Expanding spaces and new global regulatory trends](https://www.researchgate.net/publication/359603963_Educational_Privatization_Expanding_spaces_and_new_global_regulatory_trends_in_educational_privatization). In: F. Rizvi, B. Lingard, & R. Rinne (Eds.) *Reimagining Globalization and Education* (pp. 105-119). London: Routledge.

-   Zancajo, A., & Valiente, O. (2019). [Evolución de las políticas de ETP en Chile: entre el capital humano y el derecho a la educación](https://books.google.es/books?id=K5XIDwAAQBAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false). In L. Sepúlveda & M.J. Valdebenito (Eds.) *Educación Técnico Profesional ¿Hacia dónde vamos?: políticas, reformas y nuevos contextos de desarrollo*. Ediciones Universidad Alberto Hurtado: Santiago de Chile.

-   Bonal, X., & Zancajo, A. (2018). [School segregation in the Spanish quasi-market education system: local dynamics and policy absences](https://www.researchgate.net/publication/346835932_School_Segregation_in_the_Spanish_Quasi-market_Education_System_Local_Dynamics_and_Policy_Absences). In X. Bonal & C. Bellei (Eds.) *Understanding school segregation: patterns, causes and consequences of spatial inequalities in education* (pp. 201-220). London, UK: Bloomsbury.

-   Verger, A., Zancajo, A., & Fontdevila, C. (2018). [Experimenting with educational development: International actors and the promotion of private schooling in vulnerable contexts](https://www.academia.edu/37900928/Experimenting_with_educational_development_international_actors_and_the_promotion_of_private_schooling_in_vulnerable_contexts). In G. Steiner-Khamsi & A. Draxler (Eds.), *The State, Business and Education: PPPs Revisited* (pp. 16-38). Cheltenham UK/Northampton, MA: Edward Elgar.

-   Fontdevila, C., Verger, A., & Zancajo, A. (2017). [Taking advantage of catastrophes: education privatization reforms in contexts of emergency](https://link.springer.com/chapter/10.1007/978-3-658-17104-9_13). In T. Koinzer, R. Nikolai and F. Waldow (Eds.) *Private Schools and School Choice in Compulsory Education. Global Change and National Challenge* (pp. 223-244) Wiesbaden, Germany: Springer VS.

-   Verger, A., Fontdevila, C. and Zancajo, A. (2017). Privatization by Default in Low-Income Countries: The emergence and Expansion of Low-Fee Private Schools. In A. Verger, H.K. Altinyelken & M. Novelli. *Global Education Policy and International Development. New Agendas, Issues and Policies* (2nd edition) (pp. 255-276). London, UK: Bloomsbury Academic.

-   Ferrer, F.; Castejón, A., & Zancajo, A. (2013). [Joventut i educació en temps de crisi. In P. Serracant, P. (Ed.). Enquesta de joventut de Catalunya 2012](https://ddd.uab.cat/pub/caplli/2013/171177/enqjovcat_a2013v1p77.pdf). Barcelona: Departament de Benestar i Família.

## Reports and working papers {#reports-page}

-   Fontdevila, C., Verger, A., & Zancajo, A. (2024). [*NEPC Review: Spark & Sustain How All the World’s School Systems Can Improve Learning at Scale (McKinsey & Company, February 2024)*](https://nepc.colorado.edu/review/learning). National Education Policy Center.

-   Bonal, X., Ferrer, G., & Zancajo, A. (2023). [*Desigualdades socioespaciales en la educación en Euskadi*](https://www.researchgate.net/publication/369184660_Desigualdades_socioespaciales_en_la_educacion_en_Euskadi). Instituto Vasco de Investigación y Evaluación Educativa.

-   Zancajo, A., Fontdevila, C., Verger, A., & Bonal, X. (2021). [*Regulating Public-Private Partnerships, governing non-state schools: An equity perspective*](https://unesdoc.unesco.org/ark:/48223/pf0000380092). Background paper elaborated for the 2021 Global Education Monitoring Report.

-   Zancajo, A. (2021). [*The impact of the Covid-19 pandemic on education. Rapid review of the literature*](https://www.thebritishacademy.ac.uk/documents/3226/COVID-decade-The-impact-on-education-Rapid-review-Adrian-Zancajo-Glasgow.pdf). Paper elaborated for the ‘COVID-19 and Society’ British Academy project.

-   Zancajo, A. (2019*). [Drivers and Resistances to Regulation of Education Markets: The Political Economy of the Chilean Reform](https://ncspe.tc.columbia.edu/working-papers/files/WP239.pdf)*. (National Center for the Study of Privatization in Education, Working Paper 239), Teachers College, Columbia University.

-   Bonal, X., & Zancajo, A. (2019). [*Equivalència territorial en la planificació educativa a Barcelona: Diagnòstic i propostes*](https://www.edubcn.cat/rcs_gene/extra/01_documents_de_referencia/Equivalencia_BCN_final_v2_20190320.pdf). Consorci d’Educació de Barcelona

-   Verger, A., Bonal, X., & Zancajo, A. (2015). [*Indicators for a Broad and Bold Post-2015 Agenda: A Comprehensive Approach to Educational Development*](https://www.opensocietyfoundations.org/sites/default/files/verger-indicatiors-broad-bold-20150520.pdf). Open Society Foundations.
