---
title: CV
format:
  quarto-cv-pdf: default
author: Adrián Zancajo
address: "Edifici E · Campus UAB · Cerdanyola del Vallès 08193, Spain"
email: adrian.zancajo@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
#github: github # github account
orcid: 0000-0002-4431-8155 # orcid identifier
#osf: ymqui # osf five character id
#twitter: AdrianZancajo
linkedin: azancajo
gscholar: mJmENSwAAAAJ
academia: uab.academia.edu/AdrianZancajo
researchgate: Adrian-Zancajo-2
web: azancajo.github.io
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: articles.bib
  books: books.bib
  chapters: book_chapters.bib
  reports: reports_and_working_papers.bib
validate-yaml: false
csl: apa-cv-numbered.csl
---

# Education

\begin{tabular}{@{}p{1cm}p{15cm}@{}}
2017: & \textbf{PhD in Sociology}, Autonomous University of Barcelona. \\[2pt]
2012: & \textbf{M.Sc. in Education Research}, Autonomous University of Barcelona. \\[2pt]
2009: & \textbf{B.A. in Economics}, Autonomous University of Barcelona. \\
\end{tabular}

# Academic positions

\begin{tabular}{@{}p{4.9cm}>{\raggedright\arraybackslash}p{11cm}@{}}
\mbox{September 2022--present:} &
\textbf{'Ramón y Cajal' Senior Researcher}\newline
Department of Sociology, Autonomous University of Barcelona. \\[5pt]
\mbox{September 2021--June 2022:} &
\textbf{Lecturer in Education}\newline
Manchester Institute of Education, The University of Manchester. \\[5pt]
\mbox{January 2019--August 2021:} &
\textbf{British Academy Postdoctoral Fellow}\newline
School of Education, University of Glasgow. \\[5pt]
\mbox{October 2017--December 2018:} &
\textbf{MOVE-IN Louvain Postdoctoral Fellow}\newline
GIRSEF, Catholic University of Louvain. \\[5pt]
\mbox{February 2013--August 2017:} &
\textbf{Research Fellow (Education Policy and International Development)}\newline
Department of Sociology, Autonomous University of Barcelona. \\
\end{tabular}

# Publications

## Articles in peer-reviewed journals

::: {#refs-peer}
:::

## Books

::: {#refs-books}
:::

## Book chapters

::: {#refs-chapters}
:::

## Policy reports and working papers

::: {#refs-reports}
:::

# Research projects and contracts

## Competitive calls

1.  **Teacher attraction, retention, and stratification: Analysis of the determinants of teacher attraction, stability, and stratification for improving public policies**. Funding body and call: Spanish Foundation for Science and Technology (Fecyt). Principal Investigator: Sheila González (University of Barcelona). Starting date and duration: 1/04/2024, 2 years. Amount: 60,700€. Ref.: 21061. Participation: Researcher.

2.  **Effects of Gentrification on Education Inequalities**. Funding body and call: Spanish Agency of Research. Principal Investigator: Xavier Bonal and Adrián Zancajo (Autonomous University of Barcelona). Starting date and duration: 01/09/2023, 3 years. Amount: 60,375€. Ref.: PID2022-137183NB-I00.

3.  **School desegregation policies in the city of Barcelona: impact and mechanisms**. Funding body and call: Municipality of Barcelona (Grants for young and emerging research projects 2022). Principal Investigator: Adrián Zancajo (Autonomous University of Barcelona). Starting date and duration: 22/12/2022, 1.5 years. Amount: 58,453€. Ref.: 22S09373-001.

4.  **Is it Possible to Decommodify Education? Evidence and Lessons from the Chilean Education Market Reform**. Funding source: British Academy. Principal investigator: Dr Adrián Zancajo. Starting date and duration: 01/01/2019, 3.5 years. Amount: £305,310. Ref.: PF2\\180006

5.  **Governing the educational and labour market trajectories of secondary TVET graduates in Chile**. Funding body and call: RCUK (Newton Fund). Principal Investigator: Oscar Valiente (University of Glasgow). Starting date and duration: 01/02/2016, 3 years. Amount: £206,698. Participation: Co-Principal Investigator. Ref.: ES/N019229/1.

6.  **Public-Private Partnerships in Educational Governance: An analysis of its dissemination, implementation and impact in a globalizing world**. Funding body and call: European Commission (FP7-PEOPLE-2011-CIG). Principal Investigator: Antoni Verger (Autonomous University of Barcelona). Starting date and duration: 01/02/2013, 4 years. Amount: 100.000€. Participation: Research fellow. Ref: GA-2012-322350

7.  **The new quasi-market reforms in education in Latin America. An analysis of policy processes and policy impacts on inequalities and poverty**. Funding body and call: Spanish Ministry of Science (Proyectos de investigación no orientada). Principal Investigator: Xavier Bonal and Antoni Verger (Autonomous University of Barcelona). Starting date and duration: 01/01/2012, 3 years. Amount: 50,000€. Participation: Researcher. Ref.: CSO2011-22697.

## Research contracts

1.  **Study of the impact of school zoning in Tarragona**. Principal Investigator: Adrián Zancajo (Autonomous University of Barcelona). Funding body: Municipality of Tarragona. Starting date and duration: 22/10/2024, 9 months. Amount: 14,519.88€

2.  **School dropout in Catalonia. Statistical and geographical analysis**. Principal Investigator: Adrián Zancajo (Autonomous University of Barcelona). Funding body: Fundació Bofill. Starting date and duration: 14/07/2022, 9 months. Amount: 5,000€.

3.  **An Analysis of Teacher Shortages in sub-Saharan Africa and Southern Asia**. Principal Investigator: Adrián Zancajo (Autonomous University of Barcelona). Funding body: Teachers Task Force—UNESCO. Starting date and duration: 01/07/2022, 3 months. Amount: 2,000€.

4.  **Socio-spatial inequalities in education in Euskadi**. Principal Investigator: Xavier Bonal (Autonomous University of Barcelona). Funding body: Basque Institute for Educational Evaluation and Research. Starting date and duration: 15/05/2022, 9 months. Amount: 14,500€.

5.  **Regulating Public-Private Partnerships, governing non-state schools: An equity perspective**. Principal Investigator: Adrián Zancajo (University of Glasgow). Funding: UNESCO. Starting date and duration: 15/05/2020, 6 months. Amount: 10,000 US \$.

6.  **The model of private subsidised education under debate. An international and comparative perspective**. Principal Investigator: Antoni Verger (Autonomous University of Barcelona) and Adrián Zancajo (University of Glasgow). Funding: Fundació Bofill. Starting date and duration: 01/12/2019, 10 months. Amount: 20,297€.

7.  **Equivalence criteria in Barcelona’s educational planning: Diagnosis and proposals**. Principal Investigator: Xavier Bonal (Autonomous University of Barcelona) and Adrián Zancajo (Catholic University of Louvain). Funding: Barcelona Education Consortium. Starting date and duration: 01/05/2017, 1 year. Amount: 26,000€.

8.  **Formulating Potential Indicators for a Broad and Bold Global Education Agenda for Post-2015**. Principal Investigator: Antoni Verger, Xavier Bonal and Adrián Zancajo (Autonomous University of Barcelona). Funding: Open Society Foundations (OSF). Starting date and duration: 21/05/2015, 9 months. Amount: 10,000 US \$.

9.  **Educational Inequalities and public-private partnerships in Colombian Education**. Principal investigators: Professor Antoni Verger and Professor Xavier Bonal. Funding institution: Open Society Foundations (OSF). Starting date and duration: 21/05/2015, 9 months. Amount: £15,936

10. **The political economy of education privatization. A systematic review**. Principal Investigator: Antoni Verger (Autonomous University of Barcelona). Funding: Education International. Starting date and duration: 10/01/2015, 1 year. Amount: 23,000€.

11. **PISA 2012 in Catalonia**. Principal investigator: Professor Xavier Bonal. Funding institution: Fundació Jaume Bofill. Starting date and duration: 18/01/2014, 1 year. Amount: £19,381

12. **Catalan Youth Survey 2012- Education**. Principal investigators: Adrián Zancajo and Alba Castejón. Funding institution: Observatori Català de la Joventut. Starting date and duration: 12/09/2012, 6 months. Amount: £2,584

13. **TVET and Employment in Catalonia**. Principal investigator: Dr Oscar Valiente. Funding institution: Fundació Jaume Bofill. Starting date and duration: 10/03/2012, 9 months. Amount: £21,535

14. **PISA – 2009 in Catalonia**. Principal investigator: Professor Ferran Ferrer. Funding institution: Fundació Jaume Bofill. Starting date and duration: 12/01/2012, 9 months. Amount: £17,228

15. **The measure of educational development**. Principal investigators: Professor Xavier Bonal and Professor Antoni Verger. Funding institution: International Institute for Educational Planning – UNESCO. Starting date and duration: 05/09/2011, 5 months. Amount: £7,752

# Invited presentations

- ***School Choice and Socio-Spatial Inequalities: The Role of Geography***. Department of Geography, J. E. Purkyně University. 14th of April 2026. Ústí nad Labem, Czech Republic.

- ***Development paradigms and TVET policies in Chile. Suitable development at human scale: What do we expect from vocational education?*** Seminar organised by the Chilean Ministry of Education. 31st of August 2022. Santiago, Chile.

- ***Regulating education PPPs: an equity perspective***. Second global meeting of the Education Finance Network organised by the United States Agency for International Development (USAID). 9th of June 2022. Online.

- ***Is it possible to balance education markets and equity? An international approach to the regulation of pro-market policies in education***. The Ideas Lab, University of Cambridge. 18th of November 2021. Online.

- ***Vocational education policies in Chile (2006-2018). Views of presidential candidacies on the future of the vocational education in Chile***. Seminar organised by Aequalis. 2nd of November 2021.

- ***Private subsidised schools: Proposals of educational policy***. Seminar organised by Eusko Ikaskuntza. 22nd of October 2021.

- ***Paths towards privatisation: a political economy approach. Education and training policies for social inclusion and sustainable development in Chile and Latin America***. Seminar organised by Chile Global Seminars UK. 26th of September 2018. Glasgow, United Kingdom.

# Research visits

- April 2026: **Department of Geography**, J. E. Purkyně University.

- March-June 2016: **Robert Owen Centre for Educational Change**, University of Glasgow.

- March-June 2015: **Centre for Advanced Research in Education**, University of Chile.

# Teaching and supervision

## Undergraduate

- *Education Policy*. BA in Sociology, Autonomous University of Barcelona. Academic years: 2022/23, 2024/2025.

## Graduate

- *Social Justices Theories in Education*. Erasmus Mundus Master's Degree in Education Policies for Global Development, Autonomous University of Barcelona. Academic years: 2022/23, 2024/2025, 2025/2026.

- *Concepts and Practices of International Education*. MA International Education. The University of Manchester. Academic year: 2021/22.

- *Educational Research Methods and Design*. MA International Education. The University of Manchester. Academic year: 2021/22.

- *Equality, Diversity and Inclusion in International Education*. MA International Education. The University of Manchester. Academic year: 2021/22.

- *Advanced Policy Enquiry*. Masters in Education, Public Policy & Equity. University of Glasgow. Academic years: 2019/20, 2020/21.

## PhD supervision

- Kon-turi Atan (Autonomous University of Barcelona). *Educational Inequalities in Rapa Nui: An Intersectional Analysis of Cultural Assimilation and Community Resistance (1939–1988).*

- Carlos Bueno (Autonomous University of Barcelona). *The journey to school: Sociospatial approaches on access to education in Medellín.*

- Juan Antonio Carrasco (Autonomous University of Barcelona). *Policy Adoption and Responses to Regulatory Pressure in Private Schools: The Case of the School Inclusion Law in Chile (2015–2020).*

- José Antonio Cervantes (University of Glasgow). *Youth building the future: The political economy of the adoption of a youth policy in Mexico.* Awarded, 2025.

- Alice Aldinucci (University of Glasgow). *Understanding aspirations and choices of upper-secondary TVET students in transition to postschool trajectories in Chile.* Awarded, 2022.

# Awards and grants

- 2023 Best Paper. Journal of Vocational Education & Training.

- 2019 Best Paper. Journal of Vocational Education & Training.

- 2018 Best Doctoral Dissertation. Comparative and International Education Society’s Globalization and Education SIG.

- 2016 Best Book on Globalization and Education. Comparative and International Education Society’s Globalization and Education SIG.

- 2015 Ibero-American Young Researchers' Grant. Banco Santander.

# Academic service

- Member of the evaluation committee of 2023 ‘Juan de la Cierva’ postdoctoral fellowships call (Spanish Agency of Research).

- External evaluator of the 2019 Youth Futures Programme (British Academy) and 2024 Fondecyt call (Chilean National Research and Development Agency).

- Editor of *Papers. Revista de Sociologia* since 2022.

- *Reviewer for the academic journals: British Educational Research Journal, British Journal of Sociology of Education, Community, Work & Family, Compare: A Journal of Comparative and International Education, Comparative Education Review, Critical Studies in Education, Educação & Sociedade, Education Inquiry, Education Policy Analysis Archives, European Educational Research Journal, Globalisation, Societies and Education, International Journal of Education and Development, Journal of Adult & Continuing Education, Journal of Education Policy, Journal of Vocational Education & Training, Regulation & Governance, Research In Comparative and International Education, Review of Education, Review of Educational Research, Revista Internacional de Sociología (RIS), Social Science Research, The International Journal of Human Rights, Urban Studies.*
